### ISSUE TITLE
直播7天实现一个raft!!!

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/traft#1]
都说deadline 是第一生产力. 放假没事, 试试看能不能7天写个raft出来, 当练手了. 2021-02-09
装逼有风险, 万一写不出来也别笑话我.

# Features:

- [ ] Leader election
- [ ] WAL log
- [ ] snapshot
- [ ] member change with generalized joint consensus.
- [ ] Out of order commit/apply if possible.

# Day-0 2021-02-09

- [x] TailBitmap to support for describing log dependency etc. see: https://github.com/openacid/low/blob/ci/bitmap/tailbitmap.go

# Day-1 2021-02-10

- [x]: design t-raft protobuf

# Day-2 2021-02-11

- [x]: design t-raft protobuf
- [x]: impl handle_vote

# Day-3 2021-02-12

- [ ]: refactor concepts
- [ ]: impl traft main-loop
- [ ]: test handle_vote

**Comment by dddinary** [comment]
追更

**Comment by drmingdrmer** [comment]
> 追更

˙–˙好
